import StaticSanityCheck.StaticLimit
import StaticSanityCheck.MinkowskiLinearTilt
import StaticSanityCheck.DeSitterPG
import StaticSanityCheck.K2General
import StaticSanityCheck.DeSitterPG_FromGeneral
import StaticSanityCheck.AbstractAverage
import StaticSanityCheck.IRDominance
import StaticSanityCheck.DeSitterWellPosed

-- re-export convenience
